name: build
'on':
  - push
jobs:
  aws-stack:
    runs-on: ubuntu-latest
    name: build nextjs app
    steps:
      - uses: actions/checkout@v2
          with:
            ref: development
            persist-credentials: false

      - name: 'use node.js v14'
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
          registry-url: 'https://registry.npmjs.org/'

      - name: install dependencies
        run: npm install

      - name: run build
        run: npm run build

      - name: run tests
        run: npm test
        env:
          CI: true
          FORCE_COLOR: 1